In [6]:
import pandas as pd

# Now we need to read in the data
df = pd.read_csv(r"C:\Users\Marjan\Desktop\BigDataPortfolio\frenepublicinjection2016.csv")

#count the number of rows:

print(len(df))
df.head()

27244

,Nom_arrond,Invent,no_civiq,Rue,Rue_De,Rue_A,Nom_parc,Sigle,Injections,x,y,longitude,latitude
0,Ahuntsic-Cartierville,R,9805,"Sacré-Coeur, avenue du","Sauvé Est, rue","Sauriol Est, rue",NaN,FRPE,2016,292946.888016,5.046548e+06,-73.651829,45.558747
1,Ahuntsic-Cartierville,R,9825,"Sacré-Coeur, avenue du","Sauvé Est, rue","Sauriol Est, rue",NaN,FRPE,2016,292923.835994,5.046556e+06,-73.652124,45.558819
2,Ahuntsic-Cartierville,R,9810,"Sacré-Coeur, avenue du","Sauvé Est, rue","Sauriol Est, rue",NaN,FRPE,2016,292944.121003,5.046531e+06,-73.651864,45.558594
3,Ahuntsic-Cartierville,R,10432,"Lille, rue de","Fleury Est, rue","Prieur Est, rue",NaN,FRPE,2016,293044.305983,5.048354e+06,-73.650624,45.575000
4,Ahuntsic-Cartierville,R,1170,"Louvain Est, rue de","Christophe-Colomb, avenue","De Bretonvilliers, avenue",NaN,FRPE,2016,293425.855011,5.046560e+06,-73.645694,45.558863